### ISSUE TITLE
Add an interface to report if an overflow has occurred

### ISSUE THREAD

**Issue by fjahn** [borgar/textbox#9]
It would be very helpful to have a way to make the font size decrease if the text would not be able to fit otherwise. There could be an option to define a minimum font size.

**Comment by borgar** [comment]
Because changing font size affects how text flows into the given bounds, the only way to know if the text fits a box is to run `.linebreak()` with different font sizes and test the results.

What you suggest could be made by linebreaking and testing for overflow, decreasing the font size and trying again until the text either fits or a minimum font size is reached:

```js
let fSize = 14;
const box = new Textbox({ width: 150, height: 150 });
while (fSize >= 10) {
  box.font(font: fSize + 'px/14px sans-serif');
  const lines = box.linebreak( textPassage );
  if (/* if there is no overflow */) {
    break;
  }
  fSize--;
}
// ... render the lines
```

This is not something I would like to include for two reasons:

* This is simple to do from the outside, so there is no big need for the library to do this, except as convenience.
* This is slow and internalizing it in the library would hide that from you. I would much rather that users are aware that doing this is not performant.

That being said, it should actually be *possible* to implement the above. And the output from the linebreak function should be tagged with an indicator whether the text fit or not:

```js
let fSize = 14;
const box = new Textbox({ width: 150, height: 150 });
while (fSize >= 10) {
  box.font(font: fSize + 'px/14px sans-serif');
  const lines = box.linebreak( textPassage );
  if (lines.fit) { // ← the missing link
    break;
  }
  fSize--;
}
// ... render the lines
```

**Comment by fjahn** [comment]
I agree with your arguments. I like your proposal for the interface, but I would suggest to call the property `overflows` or `hasOverflow` instead of `fit`, because for me `fit` could mean other things, and it also could be a method instead of a value.

---

I actually did implement it like your code sample already. The way I detect if there is an overflow is to call `linebreak` with `height` set to `Infinity` and check if it fits the actually desired height afterwards. I would still prefer a cleaner way to have _Textbox_ to tell me if there was an overflow or not. Not only because it would be cleaner, but also because it performs better:

I assume that the placement calculations are aborted as soon as there is no space left. If a text is 100 lines long, but there is only room for 3, it is still pretty fast because not all 100 lines have to be calculated. With my hacky solution, however, all 100 lines are always calculated, which is unnecessarily slow. What makes it even worse is that the loop runs pretty often until eventually, the font size becomes small enough to fit all of the text.

**Comment by borgar** [comment]
> I assume that the placement calculations are aborted as soon as there is no space left.

Yes. You are right, it does abort and it would be much more performant to get the notification rather than using something like your workaround. I definitely want to add this!

**Comment by fjahn** [comment]
Great! If you are satisfied with my proposal for the interface, I could work on a PR!
